try:
  print(n1)
except:
  print("An exception occurred")